language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t testingtrail/react -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true testingtrail/react npm test

after_success:
    - docker build -t qaguy/multi-client ./client
    - docker build -t qaguy/multi-nginx ./nginx
    - docker build -t qaguy/multi-server ./server
    - docker build -t qaguy/multi-worker ./worker

    # log in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io

    # take those images and push them to docker hub
    - docker push qaguy/multi-client
    - docker push qaguy/multi-nginx
    - docker push qaguy/multi-server
    - docker push qaguy/multi-worker

# deploy:
#     edge: true
#     provider: elasticbeanstalk
#     region: "<yourregionasappearintheURL>"
#     app: <yourappinaws>
#     env: "<yourenvironmentname>"
#     bucket_name: "<theS3bucketwheretheappwasstored>"
#     bucket_path: "<samenameasappname"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY

